<a href="https://colab.research.google.com/github/19k41a0516/AI/blob/main/KERNEL%20SVM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

KERNEL SVM

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
irisdata = pd.read_csv('/content/drive/MyDrive/SVM')
print(irisdata.head())

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa


In [ ]:
X = irisdata.drop('Species', axis=1)
y = irisdata['Species']

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [ ]:
from sklearn.svm import SVC
svclassifier = SVC(kernel='poly', degree=8)
svclassifier.fit(X_train, y_train)

SVC(degree=8, kernel='poly')

In [ ]:
y_pred = svclassifier.predict(X_test)

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[ 9  0  0]
 [ 3  6  0]
 [ 0  0 12]]
                 precision    recall  f1-score   support

    Iris-setosa       0.75      1.00      0.86         9
Iris-versicolor       1.00      0.67      0.80         9
 Iris-virginica       1.00      1.00      1.00        12

       accuracy                           0.90        30
      macro avg       0.92      0.89      0.89        30
   weighted avg       0.93      0.90      0.90        30

